### ISSUE TITLE
AppImage target

### ISSUE THREAD

**Issue by 5paceToast** [roma-apps/roma-desktop#21]
## Describe
Using the appimage target in electron-builder to generate appimage distributables in releases.

## Why
The appimage format is intended to work across linux distributions, but follows a "one app, one file" approach, closer to MacOS, which is more convenient for end-users.
If set up to do so (via zsync + built-in metadata), it can also provide a convenient system to fetch latest updates.

Electron-builder should already have an appimage target that simply needs to be used, so the upfront cost for initial testing is fairly low.

**Comment by h3poteto** [comment]
I released version 2.0.0 with AppImage build.
https://github.com/roma-apps/roma-desktop/releases/tag/v2.0.0
