### ISSUE TITLE
[question] Whalebird or Roma?

### ISSUE THREAD

**Issue by ITwrx** [roma-apps/roma-desktop#28]
i'm confused by your repos. Both Whalebird and Roma-desktop are being updated, so i don't understand why you are maintaining both repos and which one i should use. Not sure which is newer either. Whalebird latest version is 4.1.0 and Roma is 3.0.1. Finally, if you are able to package into so many formats how come they are not submitted to the distros so people can use their package manager to keep updated?

thanks

**Comment by h3poteto** [comment]
Roma is an official client for Pleroma and it is based on Whalebird.
Those two's source code are slightly different, but provides almost the same functionality. So please use whichever one you prefer.

I'm developing Whalebird, and I update Roma after I update Whalebird. So those tow versions don't match up.

**Comment by ITwrx** [comment]
ok, thanks
